runner:
  total_steps: 20000
  gradient_clipping: 1
  gradient_accumulate_steps: 1
  log_step: 300
  eval_step: 300
  save_step: 300
  max_keep: 1
  eval_dataloaders: 
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-2

downstream_expert:
  datarc:
    singer_file_path: "/home/johnwei743251/dataset/VocalSet"
    singer_meta_data: "/home/johnwei743251/dataset/singer_id/meta_data/data"
    fluent_file_path: "/home/johnwei743251/dataset/fluent_speech_commands_dataset"
    num_workers: 8
    train_batch_size: 64
    eval_batch_size: 1

  modelrc:
    projector_dim: 512
    select: UtteranceLevelMultiTask
    UtteranceLevel:
      pooling: MeanPooling 
